### PR TITLE
Show 0 resources if selector doesn't devices or no RDMA devices found for selected devices

### LINKED ISSUE #4: The plugin doesn't fail when the net device doesn't exist
**Current Behavior:**
When pass a config like:
```
    {"configList": [{
             "resourceName": "hca_shared_devices_a",
             "rdmaHcaMax": 1000,
             "devices": ["ib0", "ib1","ib99"]
           }]}
```
and the device `ib99` doesn't exist in the host then plugin just skip it without failing.

**Expected Behavior:**
The plugin should fail if there is any missing device.

### PR DESCRIPTION
**Pull request by Mmduh-483**
Show zero resources when no RDMA devices are found

Today, device plugin falsely publishes available RDMA resources to kubelet
even though a device does not exit or doesn't actually have RDMA resources.

This commit fixes the issue by performing the needed checks ensuring the pool
has a root device with RDMA resources before publishing available resources for the
pool

fixes #4

### CODE REVIEW

File: pkg/types/types.go [hunk 1]
```diff
@@ -57,3 +57,8 @@ type ResourceServerPort interface {
 type SignalNotifier interface {
 	Notify() chan os.Signal
 }
+
+// RdmaFinder used to find the rdma devices
+type RdmaFinder interface {
```
Comment (adrianchiris) [inline pkg/types/types.go:62]: i think this interface represents a device's RDMA spec right ?

you could name the interface : `RdmaDeviceSpec`
it would then have a `Get(pciAddress string)` method to retrieve ther 

WDYT ?

File: pkg/resources/server_test.go [hunk 2]
```diff
@@ -357,7 +377,13 @@ var _ = Describe("resourceServer tests", func() {
 	})
 	Context("ListAndWatch", func() {
 		It("Get devices of plugin and change device status", func() {
-			obj, err := newResourceServer(&types.UserConfig{RdmaHcaMax: 100, ResourceName: "fake"}, true, "fake", "fake")
+			fs := utils.FakeFilesystem{
```
Comment (adrianchiris) [inline pkg/resources/server_test.go:380]: Why do you need a fake filesystem now ? 
was it needed before and it was a bug that fake filesystem was not used ?

File: pkg/resources/server.go [hunk 3]
```diff
@@ -357,7 +360,10 @@ func (m *resourceServer) NotifyRegistrationStatus(ctx context.Context, regstat *
 	return &registerapi.RegistrationStatusResponse{}, nil
 }
 
-func getRdmaDeviceSpec(pciAddress string) []*pluginapi.DeviceSpec {
+type rdmaFinder struct {
```
Comment (adrianchiris) [inline pkg/resources/server.go:363]: consider moving RdmaFinder and its implementation into its own package for cleaner code partitioning.

File: pkg/resources/server_test.go (hunk 2 above)
Comment (Mmduh-483) [reply pkg/resources/server_test.go:380]: The previous behavior allows creating the resources even if the devices doesn't exist or there is empty list of devices, this test was depending on the second case.

File: pkg/types/types.go (hunk 1 above)
Comment (Mmduh-483) [reply pkg/types/types.go]: Seems good, adopted

**Comment by moshe010** [comment]
can you update in the PR what is the change and what issue it fixes?

**Comment by adrianchiris** [comment]
>Show 0 resources if selector doesn't devices or no RDMA devices found for selected devices
>
>This commit fix the issue of the device plugin is falsely publish
>available RDMA resources to kubelet even though a device does not
>exit or doesn't actually have RDMA resources

Suggestion for a reword to:
1. One line short description of this commit
2. describe the issue
3. describe the solution

Show zero resources when  no RDMA devices are found

Today, device plugin falsely publishes available RDMA resources to kubelet
even though a device does not exit or doesn't actually have RDMA resources.

This commit fixes the issue by performing the needed checks ensuring the pool
has a root device with RDMA resources before publishing available resources for the
pool.

**Comment by adrianchiris** [comment]
LGTM

File: pkg/resources/server.go [hunk 4]
```diff
@@ -114,28 +115,30 @@ func newResourceServer(config *types.UserConfig, watcherMode bool, resourcePrefi
...
+		for n := 0; n < config.RdmaHcaMax; n++ {
+			id := n
+			dpDevice := &pluginapi.Device{
+				ID:     strconv.Itoa(id),
+				Health: pluginapi.Healthy,
+			}
+			devs = append(devs, dpDevice)
+		}
+	}
+
```
[the remark this answers is not in the document]
Comment (Mmduh-483) [reply pkg/resources/server.go:143]: Added
